language: java
jdk:
- oraclejdk8
install: true
script: gradle clean build jar
cache:
  directories:
  - "$HOME/.gradle"
deploy:
  provider: releases
  api_key:
    secure: Zgk3YFEi6WBo8XkLnZbqEOW68vBqkZp0spbvs2OJZfMsPNjjFusP4OEuBeKtW6jFpvvk//m9nodyoAvlG5HwF2/hNSqYfjLZEa+r8PeiDCocKJ5FNrqQevOCciz3elm+RHSBebM6lZx2dhUBuTsFvFLnV3h0E14/2neqWd5Wsk3XXTSXky+hQFQgru9kG4ATSX+5hsYVm3KFP3tX/hbFu0WaIeIfX6iCSoYZbkA0wbvP235O4v6dm3z1TIuH2uW19R2wORRtqdD4pAhWBC6ddf9C6GLuYor5PX6qsZ/9LuXsJra+qDjfjlxRy1J+adC0FMx5Vu6cSiW4KkJ5kqZ6ndegiFdj+FeHnulrT9DV7+bn9jFOI0Z5nTMU+fJ5T/QjKzUW63J9k2xusTE2nfN4BCtK5SV8Hqm+URkHlaeHo9Dp5VXiquN/9cZTV2utbF2A6P6hw45BDJtZoNf5l1L01v5Xf1sqSkTLjq6b3b1/2f8jS4Gx9wGV00JJxGgGLxirfJQZ5Fc0jXXG0nmnsj9p6I98nXgogRoyyWMdz1UbsNVAdKi06IqeI9p0XrblTIwV8w9tVu5MemWfBP5wHks86LLbFKhRtB9ixNwl6NUkxX1ZIy8Jx6mjLHmZr7lvftC+5vdJL6Eov4lLExVScdi5JReM5M5FM8IBHJXPs/X5WVo=
  file: "./build/libs/PlaceholderAPI.jar"
  on:
    tags: true